### ISSUE TITLE
GHAS Compliance Action Default Branch Limitation

### ISSUE THREAD

**Issue by GeekMasher** [advanced-security/policy-as-code#2]
**Describe the bug**

- https://github.com/GeekMasher/advanced-security-compliance/issues/33
- https://github.com/GeekMasher/advanced-security-compliance/issues/72

**Comment by GeekMasher** [comment]
@oliveiraleom / @HaleenUptain the limitations of which branches the engine uses have been fixed for Code Scanning and Secret Scanning for GHEC/GHES.

https://github.com/advanced-security/policy-as-code/pull/9

**Comment by GeekMasher** [comment]
This is fixed with the release of v2.1

**Comment by HaleenUptain** [comment]
@GeekMasher, thanks for heads up.  We will resume component evaluation work.
