### ISSUE TITLE
Policy-as-code for non-default branch issues

### ISSUE THREAD

**Issue by karthikboncheruuvu** [advanced-security/policy-as-code#25]
### Discussed in https://github.com/advanced-security/policy-as-code/discussions/24

<div type='discussions-op-text'>

<sup>Originally posted by **karthikboncheruuvu** July  4, 2023</sup>
HI @GeekMasher ,

You are helpful and sharing knowledge on many aspects, Take a bow for your work.

I had one show stopper during my CI/CD implementation.

The question goes like this..

I tried policy-as-code for default branch it works well and fine.
but when i tried the same thing to other branches such as PT or pre-prod which are lower environements, it is fetching the non-default branch issue..

Kindly help me enabling same for non-default branch as well( we have configured codeql to non-default branch FYI)

Looking forward for quick solution.

</div>

@GeekMasher ..kindly help here

**Comment by GeekMasher** [comment]
@karthikboncheruuvu You are right and this is a bug since the migration in v2.3+. I will be creating a PR and release shortly to solve the issue.

For reference, the issue is here:

https://github.com/advanced-security/policy-as-code/blob/main/ghascompliance/checks.py#L81

**Comment by karthikboncheruuvu** [comment]
@GeekMasher , thanks for attending .
Kindly keep me posted.
As of now i am using version 2.1 as a backup for the same.

**Comment by GeekMasher** [comment]
v2.3.3 should fix the issue. I'm re-opening until you confirm the fix.

https://github.com/advanced-security/policy-as-code/releases/tag/v2.3.3

**Comment by GeekMasher** [comment]
@karthikboncheruuvu can you confirm this fixed the issue?

**Comment by karthikboncheruuvu** [comment]
Sure...
@GeekMasher : do let me know what are the changes required in below template.

if i want to run in dev and qc also.

"""" Compliance
- name: Advance Security Policy as Code
  uses: advanced-security/policy-as-code@v2.3.5
  with:
    # The owner/repo of where the policy is stored  
    policy: GeekMasher/security-queries
    # The local (within the workspace) or repository
    policy-path: policies/default.yml
    # The branch you want to target
    policy-branch: main

"""
i dont see branch name option for target repo in above snippet..Kindly help here

**Comment by GeekMasher** [comment]
@karthikboncheruuvu to change the branch from a different one the Action is running you have to set the `ref` argument of the Action like this:

```yaml
- name: Advance Security Policy as Code
  uses: advanced-security/policy-as-code@v2.3.5
  with:
    # ...
    # default is your current reference (refs/heads/{BRANCH})
    ref: "refs/heads/main"
```

**Comment by karthikboncheruuvu** [comment]
HI @GeekMasher :
Thanks i tried this but there is mismatch in codescanning results numbers.
severity is set to error, hence it should show critical and high issues if i am not wrong...

So in my case there were 1 critical and 2 high issues in codeql, but policy as code returned saying only 2 violations in codeql.

it is showing perfectly fine for default branch..can u look into it please..

**Comment by GeekMasher** [comment]
@karthikboncheruuvu In the output logs, can you see something like this (in my case `develop` is the branch):

```log
...
GitHub Repository :: advanced-security/policy-as-code
GitHub Instance :: https://github.com
GitHub Reference (branch/pr) :: refs/heads/develop
...
```

If this is set correctly, the Code Scanning check will use that as its reference.

https://github.com/advanced-security/policy-as-code/blob/main/ghascompliance/checks.py#L84

-----

Is this code in a Pull Request or just another branch?

Which of the 3 findings was not shown?
If you don't know which, [you can you enable Display mode to the Action](https://github.com/advanced-security/policy-as-code/discussions/33) to see which ones triggered the violations.

**Comment by karthikboncheruuvu** [comment]
HI @GeekMasher :

yes, all are working perfectly only mismatch in codeql violations count..

..........
GitHub Repository ::myorg/Test_Repository
GitHub Instance :: https://github.com/
GitHub Reference (branch/pr) :: refs/heads/test-2

...it was just another branch with delta changes...
 Let me try display mode and let u know the results

**Comment by GeekMasher** [comment]
@karthikboncheruuvu let me run some tests and get back to you

**Comment by karthikboncheruuvu** [comment]
Hi @GeekMasher :

in base.yml file severity is error

advance.yml (policy file)
codescanning:
  level: error


usecase: we need to violate both high and critical issue in codeql...


above only violates high..

**Comment by GeekMasher** [comment]
@karthikboncheruuvu I found the issue. So it turns out that there are [two different severity's in the API](https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28#get-a-code-scanning-alert); `severity` (old) and `security_severity_level` (new).

GHASToolkit uses the old `severity` versus the newer `security_severity_level` which uses `critical`, `high`, etc.

I am switching the toolkit to use the newer API field as this will be better. PR will be merged and `policy-as-code` will be updated.

https://github.com/GeekMasher/ghastoolkit/pull/50

**Comment by karthikboncheruuvu** [comment]
Thanks @GeekMasher : 
Please mention once you have the PR merged and any documentation if any actions or changes required from our end.

Appreciate your quick turnarounds.

**Comment by GeekMasher** [comment]
@karthikboncheruuvu The new version is merged. This shouldn't effect anything on the users end.

https://github.com/advanced-security/policy-as-code/releases/tag/v2.3.6
