### ISSUE TITLE
setup-python step fails on non Ubuntu self hosted runners

### ISSUE THREAD

**Issue by goffinfnbs** [advanced-security/policy-as-code#69]
**Describe the bug**

Non portable step within the action.

When running this action on a self hosted non Ubuntu distro (we use RHEL self hosted runners internally) the setup-python step within the action.yml fails with the error:

```
Run actions/setup-python@v4
Installed versions
  Version 3.10 was not found in the local cache
  Error: The version '3.10' with architecture 'x64' was not found for this operating system.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

This is a known issue, discussions around can be seen here:

[Version 3.10 with arch x64 not found · Issue #401 · actions/setup-python (github.com)](https://github.com/actions/setup-python/issues/401)
 
[Unable to Set-up Python · Issue #585 · actions/setup-python (github.com)](https://github.com/actions/setup-python/issues/585)

Also, for corporate use, it is common for access to the Internet to download software to be managed via a proxy, such as an Artifactory remote. In those cases setup-xxx actions may also fail.

**To Reproduce**
1. Call the action on a runner that is NOT  a recent version of Ubuntu 

**Expected behavior**
Either the action should provide an input to allow by-pass of the step (document a pre-req that a compatible version of python must be installed prior to calling the action if you don't want to (or can't) use the default) or the step should be removed entirely from the action and a pre-req added to the doc.

The problem really lays with the setup-python action, however, since that is embedded within THIS action there is no way to avoid the error other than to maintain a custom version which is not ideal.

**Screenshots**
![image](https://github.com/advanced-security/policy-as-code/assets/126687169/115d5bdc-b219-4f6f-9128-d60f236dfe44)

**Additional context**
This is a corporate environment running RHEL based self hosted GHA runners. Internet downloads for actions are only allowed via our Artifactory remotes. We can install python on our runners but ATM there is no way to skip the setup-python step within this action which will fail on RHEL.

Arguably there really shouldn't be a non-portable step inside the action !?

**Comment by sven0219** [comment]
I encountered the same problem
**/etc/os-release**
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by GeekMasher** [comment]
@goffinfnbs @sven0219 I have made some small changes to the Action `v2.6.0` which should help with this. This change is here #76 

Please let me know if this has helped

**Comment by sven0219** [comment]
HI @GeekMasher , it's works for me , thanks
**2.5.0**
![image](https://github.com/advanced-security/policy-as-code/assets/30076203/41d6c0ed-5517-4ba3-b70b-f3c6186c5ca6)
**2.6.0**
![image](https://github.com/advanced-security/policy-as-code/assets/30076203/3d619474-cff7-4492-9732-951b048cee6e)

**Comment by goffinfnbs** [comment]
@GeekMasher  I can confirm that this action DOES now operate successfully on our self-hosted runners when we run setup-python before it is called.

Looks like you took the opportunity to merge quite a number of other changes also.

I did note that you added the requirement in the announcement, but I wonder whether access to a supported version of python on the runner or installed before executing the action ought to also be documented in the README (some gnarly console output if you don't) ?

**Comment by GeekMasher** [comment]
I [started documenting this during the process](https://github.com/advanced-security/policy-as-code/blob/main/docs%2Fintroduction%2Factions.md) but I should update the README too

**Comment by GeekMasher** [comment]
Closing this issue as seems to have resolved the issue
