### ISSUE TITLE
REST Request failed :: non-expected server error

### ISSUE THREAD

**Issue by karthikboncheruuvu** [advanced-security/policy-as-code#89]
@GeekMasher : 
An unexpected exception was encountered while performing policy checks. Please report this to https://github.com/advanced-security/policy-as-code
REST Request failed :: non-expected server error

**Comment by GeekMasher** [comment]
@karthikboncheruuvu Can you share with me an details? Which step / part is the crash occurring, etc?

If this might contain sensitive information you can raise a GitHub Customer issue and tag me @GeekMasher  in it.

**Comment by karthikboncheruuvu** [comment]
HI @GeekMasher :

i am not seeing this error, after i updated it to latest. Will keep you posted if error occurs again.

thank you for your support in helping us solve the problems..Highly appreciated

**Comment by GeekMasher** [comment]
@karthikboncheruuvu Is it fine if I close out this issue now? Sounds like the new version fixed all your issues.
