### ISSUE TITLE
[Bug]: non-expected server error

### ISSUE THREAD

**Issue by Killklli** [advanced-security/policy-as-code#97]
### What happened?

So apologies as I know https://github.com/advanced-security/policy-as-code/issues/89 was opened, but I seem to be having the same issue here.

We're running on 2.7.0 and getting
```  Error: Unknown Exception was hit, please repo this to https://github.com/advanced-security/policy-as-code
  Error: REST Request failed :: non-expected server error
```

We're using this in a composite action, so we're passing in the data from there with a fairly simple call to the command.

```    - name: Advance Security Policy as Code
      uses: advanced-security/policy-as-code@v2.7.0
      with:
        # The local (within the workspace) or repository
        policy-path: ${{ github.action_path }}/default.yml
```

We do have all the permissions set at the workflow level.

```permissions:
  id-token: write
  contents: read
  checks: read
  security-events: read
  pull-requests: write
```

We've slimmed down our policy file in attempts to figure out whats going on, when we disable code-scanning it jumps through both dependabot and secrets scanning, both with errors.

For testing sake this was the YAML we ended at
```
general:
  level: error
codescanning:
  level: error
 dependabot:
  level: high
secretscanning:
  level: all
```

As a note this repo does not have vulnerabilities, while that may be the valid result when there are no errors, it is not reporting on dependabot or secret scanning, nor would throwing an error be the best response (if intended) for confusion.

### Version

v2 (current major version)

### Where are you experiencing the issue?

GitHub Actions

### Relevant log output

```shell
Run echo "Running Policy as Code..."
Running Policy as Code...
 _____  _   _   ___   _____ _____                       _ _                      
|  __ \| | | | / _ \ /  ___/  __ \                     | (_)                     
| |  \/| |_| |/ /_\ \\ `--.| /  \/ ___  _ __ ___  _ __ | |_  __ _ _ __   ___ ___ 
| | __ |  _  ||  _  | `--. \ |    / _ \| '_ ` _ \| '_ \| | |/ _` | '_ \ / __/ _ \
| |_\ \| | | || | | |/\__/ / \__/\ (_) | | | | | | |_) | | | (_| | | | | (_|  __/
 \____/\_| |_/\_| |_/\____/ \____/\___/|_| |_| |_| .__/|_|_|\__,_|_| |_|\___\___|
                                                 | |                             
                                                 |_|         v2.7.0
    GitHub Advanced Security Policy as Code by GeekMasher

GitHub Repository :: scrubbed/scrubbed
GitHub Instance :: https://github.com
GitHub Reference (branch/pr) :: refs/heads/develop
Policy as Code
  Policy config file set: /home/runner/work/_actions/scrubbed/policyascode/default.yml
  Loading policy file - /home/runner/work/_actions/scrubbed/policyascode/default.yml
  Policy loaded successfully
  Saving Policy...
  Policy saved
  Finished loading policy
Code Scanning Results
  Error: Unknown Exception was hit, please repo this to https://github.com/advanced-security/policy-as-code
  Error: REST Request failed :: non-expected server error
  Total unacceptable alerts :: 0
  Acceptable risk and no threshold reached.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karthikboncheruuvu** [comment]
HI @GeekMasher :


I am getting this error again using 2.6.0 version for one of my frontend repo.

Dependabot Results
  Error: Unknown Exception was hit, please repo this to https://github.com/advanced-security/policy-as-code
  Error: Failed to get data from GraphQL API
  
  @Killklli : +1

**Comment by ariel8300** [comment]
I get the same error, and even weirder is that there are no Results for Code Scanning although I have **2** alerts in the **Security** tab.
And the job ends as completed successfully as if everything is good
```yaml
Policy as Code
Code Scanning Results
  Code Scanning Alerts from Pull Request (alert diff)
  Total Code Scanning Alerts :: 0
  Code Scanning violations :: 0
Dependabot Results
  Dependabot Alerts from Pull Request
  Total Dependabot Alerts :: 0
  Dependabot violations :: 0
Dependency Graph
Dependency Graph Results - Licensing
Secret Scanning Results
  Secret Scanning Alerts from Pull Request
  Error: Unknown Exception was hit, please repo this to https://github.com/advanced-security/policy-as-code
  Error: REST Request failed :: non-expected server error
  Total unacceptable alerts :: 0
  Acceptable risk and no threshold reached.
```

**Comment by GeekMasher** [comment]
:wave: @Killklli Sorry for the delay in my reply. I have [released `v2.7.2`](https://github.com/advanced-security/policy-as-code/releases/tag/v2.7.2) which should address some of the issues.

The main item is better logging of what the exact issue is from GitHub instead of the `non-expected server error` which isn't helpful.

That said, during my testing I did see that Secret Scanning will error during some Action Integrations now which I haven't seen before. I'm working with the engineering team to validate this.

**Comment by GeekMasher** [comment]
@ariel8300 This might be a separate issue. Based on the logs you are running `policy-as-code` in a PR, when a `policy-as-code` is run in Pull Requests we only break on the delta of results. So if there is 2 in Security Tab for the branch but no annotations in the PR from `Code Scanning` then there is most likely not new results.

For Secret Scanning for Pull Requests we check the list of PR commits and validate to see if a secret was first seen in that PR.

Feel free to open a new issue and we can continue there.

**Comment by Killklli** [comment]
Alright so now it seems to be resource not accessible by integration, in what continues to be confusing because we're granting it the perms described in the readme.
Did something change with the permissions as well now?

```Run advanced-security/policy-as-code@v2.7.2
Run echo "Running Policy as Code..."
Running Policy as Code...
 _____  _   _   ___   _____ _____                       _ _                      
|  __ \| | | | / _ \ /  ___/  __ \                     | (_)                     
| |  \/| |_| |/ /_\ \\ `--.| /  \/ ___  _ __ ___  _ __ | |_  __ _ _ __   ___ ___ 
| | __ |  _  ||  _  | `--. \ |    / _ \| '_ ` _ \| '_ \| | |/ _` | '_ \ / __/ _ \
| |_\ \| | | || | | |/\__/ / \__/\ (_) | | | | | | |_) | | | (_| | | | | (_|  __/
 \____/\_| |_/\_| |_/\____/ \____/\___/|_| |_| |_| .__/|_|_|\__,_|_| |_|\___\___|
                                                 | |                             
                                                 |_|         v2.7.0
    GitHub Advanced Security Policy as Code by GeekMasher
GitHub Repository :: --------
GitHub Instance :: https://github.com/
GitHub Reference (branch/pr) :: refs/heads/develop
Policy as Code
  Policy config file set: /home/runner/work/_actions/-------/policyascode/default.yml
  Loading policy file - /home/runner/work/_actions/-------/policyascode/default.yml
  Policy loaded successfully
  Saving Policy...
  Policy saved
  Finished loading policy
  Policy as Code Summary:
  
  general: 'error'
  codescanning: 'error'
  dependabot: 'high'
  secretscanning: 'all'
  licensing: 'error'
  dependencies: 'error'
 
Code Scanning Results
  Error: Unknown Exception was hit, please repo this to https://github.com/advanced-security/policy-as-code
  Error: REST Request failed :: no analysis found
Dependabot Results
  Warning:  Unable to get Dependabot alerts :: REST Request failed :: Resource not accessible by integration
  Warning:  Trying GraphQL API
  Total Dependabot Alerts :: 0
  Dependabot violations :: 0
Dependency Graph
  Total Dependency Graph :: 2
  Dependency Graph violations :: 0
Dependency Graph Results - Licensing
  Loaded extra licensing information :: 9459
  Total Dependencies in Graph :: 2
  Dependency Graph violations :: 0
Secret Scanning Results
Summary
  Total unacceptable alerts :: 2
  Error: Unacceptable Threshold of Risk has been hit!
  Error: Process completed with exit code 1.
```

**Comment by GeekMasher** [comment]
@Killklli Looking at this there is a couple of things:

On the Code Scanning, there might be an issue setting up CodeQL or other security tool in Code Scanning. Maybe [checkout the Tools Status page in Code Scanning](https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/managing-your-code-scanning-configuration/about-the-tool-status-page).

On Dependabot and Secret Scanning might be the same issue and this looks like a permissions issue. Let me do some testing, discuss with engineers and get back to you. This use to work but maybe something has changed

**Comment by karthikboncheruuvu** [comment]
HI @Killklli / @GeekMasher : REST Request failed :: Resource not accessible by integration is a permission issue given at integration or pipeline level.
enable dependabot and use below permissions, everything should work fine. We had this issue and got rectified on analysis.

 permissions:
      contents: read
      id-token: write
      packages: write
      actions: read
      security-events: write

**Comment by Killklli** [comment]
That'll do it. Specifically `actions: read` is the value that needed to be added.

**Comment by karthikboncheruuvu** [comment]
HI @GeekMasher :

anyy solution for below error ?

Dependabot Results
  Error: Unknown Exception was hit, please repo this to https://github.com/advanced-security/policy-as-code
  Error: Failed to get data from GraphQL API

**Comment by GeekMasher** [comment]
@karthikboncheruuvu Does it say that `Warning Unable to get Dependabot alerts` then `Trying GraphQL API` first before these 2 GraphQL error messages?

https://github.com/advanced-security/policy-as-code/blob/main/ghascompliance/checks.py#L203-L209

**Comment by anbha15** [comment]
![image](https://github.com/advanced-security/policy-as-code/assets/61280171/6c200b80-fb90-4c5b-8543-3c398b1a5577)
Getting same error for v2.6.0. Do not understand what exactly the issue is.

**Comment by clintonste** [comment]
> @ariel8300 This might be a separate issue. Based on the logs you are running `policy-as-code` in a PR, when a `policy-as-code` is run in Pull Requests we only break on the delta of results. So if there is 2 in Security Tab for the branch but no annotations in the PR from `Code Scanning` then there is most likely not new results.
> 
> For Secret Scanning for Pull Requests we check the list of PR commits and validate to see if a secret was first seen in that PR.
> 
> Feel free to open a new issue and we can continue there.

Hi @GeekMasher  - if you're running `policy-as-code` in a PR, is there a way to block if it finds security vulnerability alerts from another branch such as main? For example my use case is that I'd like to block further merges if there are alerts that are critical or high.

**Comment by ccystephenclinton** [comment]
Hi @GeekMasher - if you're running policy-as-code in a PR, is there a way to block if it finds security vulnerability alerts from another branch such as main? For example my use case is that I'd like to block further merges if there are alerts that are critical or high.

**Comment by ccystephenclinton** [comment]
> @ariel8300 This might be a separate issue. Based on the logs you are running `policy-as-code` in a PR, when a `policy-as-code` is run in Pull Requests we only break on the delta of results. So if there is 2 in Security Tab for the branch but no annotations in the PR from `Code Scanning` then there is most likely not new results.

Hi @GeekMasher - if you're running policy-as-code in a PR, is there a way to block if it finds security vulnerability alerts from another branch such as main? For example my use case is that I'd like to block further merges if there are alerts that are critical or high.
